name: run-unit-tests
run-name: Run unit tests.
on: [push]
jobs:
  unit-test-bdd-analyser:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
      - run: rm composer.lock
      - run: composer install
      - run: ./vendor/bin/phpunit tests
